version: 0.2

phases:
  build:
    commands:
      - echo "Running security scan"
      - mkdir reports
      - echo "No vulnerabilities found" > reports/security-report.txt

artifacts:
  base-directory: website
  files:
    - "**/*"