version: 0.2

phases:
  build:
    commands:
      - echo "Creating website files"
      - mkdir -p output
      - echo "<h1>Pipeline Working 🎉</h1>" > output/index.html
      - mkdir -p output/reports
      - echo "No vulnerabilities found" > output/reports/security-report.txt

artifacts:
  base-directory: output
  files:
    - "**/*"