version: 0.2

phases:
  build:
    commands:
      - echo "Running security scan"
      - mkdir website
      - echo "<h1>My Working Site</h1>" > website/index.html
      - mkdir reports
      - echo "No vulnerabilities found" > reports/security-report.txt

artifacts:
  files:
    - website/index.html
    - reports/**/*
  discard-paths: yes